operator       = @{ "operator" } // TODO
operand        = @{ "operand" }  // TODO

instruction    = { operator ~ (" "+ ~ operand)? }

loopBlockStart = { "[" ~ ("\n" | "\r\n") }
loopBlockEnd   = { "]" }
loopBlock      = { loopBlockStart
                 ~ statements
                 ~ ("\n" | "\r\n")
                 ~ loopBlockEnd
                 }

statement      = _{ instruction | loopBlock }
statements     = _{ statement* }


file = {SOI ~ (statement ~ ("\n" | "\r\n")+)* ~ EOI}
