name: MBLF CI

on: [push]

jobs:
  build_and_format_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: cargo clippy -- -Dwarnings
      - run: cargo test
